Update packages
VisualComposer/vcwb-demo-element-example-plugin pull request #13
Opened 2021-05-05 08:26 UTC by nikitahl

2021-10-18 10:06 UTC, konutis commented on elements/cssVariablesButton/package.json
> -    "vc-webpack-vendors": "2.5.3"
why did you remove this and added dependencies separately?

2021-11-01 11:48 UTC, nikitahl commented on elements/cssVariablesButton/package.json
> -    "vc-webpack-vendors": "2.5.3"
I didn't remove it, it is still listed on line 33. At the time I was working on this task the available version of webpack vendors produced errors that couldn't be fixed due to problems with other package version numbers. But the elements weren't building, and the issue needed to be fixed.

2021-11-01 11:51 UTC, pavelthq requested changes

2021-11-01 11:51 UTC, pavelthq commented on elements/cssVariablesButton/package.json
> -    "vc-webpack-vendors": "2.5.3"
I think we should fix vendor and webpack problem first, I can help with that next extra the demo element package.json should only contain vc-webpack-vendors and few additional "resolution" packages versions

2021-11-02 09:08 UTC, pavelthq approved these changes

2021-11-02 09:09 UTC, merged